name: Bandit securityscan

on:
  push:
    branches:
      - main

env:
  VERSION: ${{github.ref_name}}

jobs:
  quality_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:

    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Requirements
      shell: pwsh
      run: |
        pip install -r requirements.txt
        pip install bandit
        foreach ($file in $(git ls-files '*.py')) { cat $file | bandit -f json - }
